name: set_jet
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  animated_theme_switcher: ^2.0.3
  cupertino_icons: ^1.0.2
  google_fonts:
  equatable: ^1.2.4
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.4.0
  flutter_chat_bubble: ^2.0.0
  shared_preferences: ^2.0.9
  get_it: ^4.0.4
  get_storage: null
  intl_phone_field: ^3.1.0
  toggle_switch: ^2.0.1
  pin_code_text_field: ^1.8.0
  logger: ^0.9.2
  page_view_indicators: ^2.0.0
  responsive_builder: ^0.2.0+2
  smooth_page_indicator: ^1.0.0+2
  stacked: ^1.7.6
  stacked_services: ^0.5.4+2
  fluttertoast: ^8.0.9
  google_sign_in: ^5.3.2
  flutter_facebook_login: ^3.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/social_Icon/
    - assets/icons/
    - assets/settingIcon/
